name: fastapi-web
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.111.0
  - uvicorn=0.30.1
  - sqlalchemy=2.0.31
  - pydantic=2.7.4
  - python-dotenv=1.0.1
  - python-multipart=0.0.9
  - pip
  - pip:
    - PyMySQL==1.1.1
    - httpx==0.27.0
    - orjson==3.10.5